### PR TITLE
Concourse issues fix

### PR DESCRIPTION
**Pull request by JasonBellONS**
# Description

Concourse update now causes git to checkout at a specific commit rather than a branch, this causes a detached head state if you attempt to push changes to the repo

If you have not checked any of the lists below explain why here.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

## **Definition of Done**
**Code and merges**

- [x] Code to be commented on where applicable 
- [x] Documentation updated where required 
- [x] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [x] I have linted the code

**Testing**

- [x] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [x] I have run the behave command to check the selenium behaviour tests pass locally
- [x] Acceptance criteria met

**Other Checks**
- [x] I have performed a self-review of my own code
- [x] I have checked for spelling errors
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes don't break anything unexpected
- [x] I have checked and updated the security.txt file where required
- [x] Up to date with the main branch

### CODE REVIEW

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d37k8elf712nkx.cloudfront.net/
cloudfront_id=E1RY0N96BCLSB4

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d37k8elf712nkx.cloudfront.net/
cloudfront_id=E1RY0N96BCLSB4

**Review by gibbardsteve — APPROVED** [review]
Looks good, how did you find out the concourse update caused this? Were you alerted by shared services or just general debug/triage on your end?

**Comment by JasonBellONS** [comment]
> Looks good, how did you find out the concourse update caused this? Were you alerted by shared services or just general debug/triage on your end?

just triage on my own end following the same checkout strategy and trying to run the commands myself initially worked until i realised it checked out a specific commit, not a branch. However looking at my emails i must have been wrong about the update, looks like it was updates regarding jen-m that i got last week that i was thinking of, it may be that this is  always how it worked but gits just managed to work with it until now for whatever reason, either way ensuring that im either on a tag/branch should fix it

**Pull request merged**
