### PR TITLE
Spp9815 thousand pounds updates

### PR DESCRIPTION
**Pull request by JasonBellONS**
# Description
 
Thousand-Pounds-Correction amended to reflect release status

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

## **Definition of Done**
**Code and merges**

- [x] Code to be commented on where applicable 
- [x] Documentation updated where required 
- [x] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [x] I have linted the code

**Testing**

- [x] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [x] I have run the behave command to check the selenium behaviour tests pass locally
- [x] Acceptance criteria met

**Other Checks**
- [x] I have performed a self-review of my own code
- [x] I have checked for spelling errors
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes don't break anything unexpected
- [x] I have checked and updated the security.txt file where required
- [x] Up to date with the main branch

### CODE REVIEW

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d2fuqe671ph6lf.cloudfront.net/
cloudfront_id=E2T5ON4LRWVMAK

**Review by jhmjam — APPROVED** [review]

**Comment by gibbardsteve** [comment]
This cannot be deployed until we have approved user documentation and a methodological sp[ecification.  The current link in the user documentation seems to go to the method spec repo and there isn't a link to the method spec (which would need to be in main - waiting on Ellie).

**Comment by JasonBellONS** [comment]
> This cannot be deployed until we have approved user documentation and a methodological sp[ecification. The current link in the user documentation seems to go to the method spec repo and there isn't a link to the method spec (which would need to be in main - waiting on Ellie).
> 
> There is also a minor typo/grammatical error on the Method Summary... The method checks the ratio of a principal variable against a suitable predictor variable and make**S** an automatic correction

Hi, yep sorry it was mentioned in standup but i forgot that you missed it, ive updated the website with temporary links to rc's etc where applicable to check the website works as intended then moved the ticket to blocked until a full release is made, ill make the changes above and change this to a draft pr to reflect that

**Review by jhmjam — DISMISSED** [review]

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d2fuqe671ph6lf.cloudfront.net/
cloudfront_id=E2T5ON4LRWVMAK

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d2fuqe671ph6lf.cloudfront.net/
cloudfront_id=E2T5ON4LRWVMAK

**Review by joepercival — APPROVED** [review]
Looks good to me

**Pull request merged**
