### PR TITLE
Spp12032

### PR DESCRIPTION
**Pull request by JasonBellONS**
Methods page amended to display contentul items in alphabetical order, when not using contentful we read from the methods directory which automatically sorts alphabetically, on contentful, content is seemingly grabbed in order or last updated. sorted method added to make the list alphabetical

### CODE REVIEW

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d12gtoc0fur356.cloudfront.net/
cloudfront_id=E3CV48CG1S24OQ

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d12gtoc0fur356.cloudfront.net/
cloudfront_id=E3CV48CG1S24OQ

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d12gtoc0fur356.cloudfront.net/
cloudfront_id=E3CV48CG1S24OQ

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d12gtoc0fur356.cloudfront.net/
cloudfront_id=E3CV48CG1S24OQ

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d12gtoc0fur356.cloudfront.net/
cloudfront_id=E3CV48CG1S24OQ

**Review by gibbardsteve — APPROVED** [review]
Approved

**Pull request merged**
