### PR TITLE
Pipenv removed & readme updated to reflect the changes

### PR DESCRIPTION
**Pull request by sanjeevz3009**
# Description

We currently have Pipenv and Poetry in the sml-catalogue repo. Pipenv was originally used in the sml-catalogue repo to create a virtual environment for the project. It was used to automatically manage project packages through the Pipfile file as you install or uninstall packages.

Down the line, we added Poetry to use for semantic versioning, which can also be used to create and manage virtual environments and manage project packages through the project.toml file.

We now don't have a need for Pipenv, thus removing Pipenv. Removed:
- Pipfile
- Pipfile.lock

If you have not checked any of the lists below explain why here.

Code comments are not necessary in this instance.

Currently, our Selenium test suite isn't working as intended. Manual checks were performed by running the web app by freshly initiating a poetry shell, poetry installing the packages and running the web app.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

## **Definition of Done**
**Code and merges**

- [ ] Code to be commented on where applicable 
- [x] Documentation updated where required 
- [x] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [x] I have linted the code

**Testing**

- [ ] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [ ] I have run the behave command to check the selenium behaviour tests pass locally
- [x] Acceptance criteria met

**Other Checks**
- [x] I have performed a self-review of my own code
- [x] I have checked for spelling errors
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes don't break anything unexpected
- [x] I have checked and updated the security.txt file where required
- [x] Up to date with the main branch

### CODE REVIEW

**Review by JasonBellONS — COMMENTED** [review]
there is some mention of pipenv in the git ignore. might be worth just removing it

**Comment by sanjeevz3009** [comment]
> there is some mention of pipenv in the git ignore. might be worth just removing it

Pipenv removed from gitignore =)

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d2lcc48gpqv614.cloudfront.net/
cloudfront_id=E1U536S1M0ZZOL

**Review by JasonBellONS — APPROVED** [review]
looks good to me

**Review by jhmjam — APPROVED** [review]

**Pull request merged**
