### PR TITLE
Introduce detailed CMS changelog information

### PR DESCRIPTION
**Pull request by gibbardsteve**
# Description

- Rename existing github workflow to correct naming error

- Introduce scripts/update_changelog.sh

- Record CMS changes in a structured format capturing:
 -- Author
 -- Environment
 -- Content Type
 -- Updated At
 -- Fields Changes 

- Updated ci/tasks/util/email_metadata.sh to work with the new format
 -- Set up additional env variables in case they are required in the email template
 
## Example CONTENTFUL_CHANGELOG.md Entry

image

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Technical Enhancements

### CODE REVIEW

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d5p2rab60njsr.cloudfront.net/
cloudfront_id=E1Q7C2DEHRAOHO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d5p2rab60njsr.cloudfront.net/
cloudfront_id=E1Q7C2DEHRAOHO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d5p2rab60njsr.cloudfront.net/
cloudfront_id=E1Q7C2DEHRAOHO

**Review by JasonBellONS — APPROVED** [review]
Looks Good to me

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d5p2rab60njsr.cloudfront.net/
cloudfront_id=E1Q7C2DEHRAOHO

**Pull request merged**
