### PR TITLE
Spp 8624 submit method content update

### PR DESCRIPTION
**Pull request by jhmjam**
# Description

Submit method has been updated with a nested list. Instead of jinja code we instead used plain html.

Tests have been checked.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

## **Definition of Done**
**Code and merges**

- [x] Code to be commented on where applicable 
- [x] Documentation updated where required 
- [x] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [x] I have linted the code

**Testing**

- [x] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [x] I have run the behave command to check the selenium behaviour tests pass locally
- [x] Acceptance criteria met

**Other Checks**
- [x] I have performed a self-review of my own code
- [x] I have checked for spelling errors
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added the JIRA ticket link to this PR
- [x] My changes don't break anything unexpected
- [x] I have checked and updated the security.txt file where required
- [x] Up to date with the main branch

### CODE REVIEW

**Comment by JasonBellONS** [comment]
Was a decision made to remove the drop down components from this page at some point? Just I recall that being a previous piece of work that was requested

**Review by JasonBellONS — DISMISSED** [review]
looks good to me

**Review by gibbardsteve — CHANGES_REQUESTED** [review]
Hi James,
We need to maintain the accordian controls.  We could maintain them by adding the html for the list/sub-list using the design system classes in the original help-methods-request.html format.

<ol class="ons-list">
        <li class="ons-list__item">My First Item</li>
        <li class="ons-list__item">My Second Item
            <ol class="ons-list">
                <li class="ons-list__item">My First Sub-Item</li>
                <li class="ons-list__item">My Second Sub-Item</li>
            </ol>
        </li>
        <li class="ons-list__item">My Third Item</li>
    </ol>

**Comment by jhmjam** [comment]
Hi @gibbardsteve ok can do this but don't we want to get rid of the html pages and use markdown instead or am i just cinfusing myself :)

**Review by gibbardsteve — APPROVED** [review]
Hi James, can you update the PR comment to match the changes that are made please.  Other than that it looks good.

**Pull request merged**
