### PR TITLE
SPP-9544-amend-github-resources-links

### PR DESCRIPTION
**Pull request by joepercival**
# Description

The links below the 'GitHub resources' heading are non-descriptive for screen reader users navigating out of the context of the page. This PR will provide more detail in the link descriptions in order to make the purpose of the links clearer.

Comments and documentation have not been provided because it is not necessary for this PR.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

## **Definition of Done**
**Code and merges**

- [ ] Code to be commented on where applicable 
- [ ] Documentation updated where required 
- [x] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [x] I have linted the code

**Testing**

- [x] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [x] I have run the behave command to check the selenium behaviour tests pass locally
- [x] Acceptance criteria met

**Other Checks**
- [x] I have performed a self-review of my own code
- [x] I have checked for spelling errors
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes don't break anything unexpected
- [x] I have checked and updated the security.txt file where required
- [x] Up to date with the main branch

### CODE REVIEW

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d3dclw6xz8ovwj.cloudfront.net/
cloudfront_id=E2KTJE7QAID0IV

**Comment by joepercival** [comment]
> I think we should retain the capitalisation of the method (since it is a name) if we can. e.g Go to Date Adjustment code on GitHub Go to Date Adjustment specification on GitHub Go to Date Adjustment user documentation on GitHub

No problem, that should be a quick fix

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d3dclw6xz8ovwj.cloudfront.net/
cloudfront_id=E2KTJE7QAID0IV

**Review by sanjeevz3009 — APPROVED** [review]
Pulled down the branch and ran it locally, tests, linting and code formatting all passed =) Steve's changes are in too. Looks good to me!

**Pull request merged**
