### PR TITLE
Spp 7308 aboutthislibrary

### PR DESCRIPTION
**Pull request by vidhyamanisankar**

### CODE REVIEW

**Review by Paul-Joel — CHANGES_REQUESTED** [review]
Should really be page_body, not page_boby

It may also be worth looking at making the template generic rather than specific for 'About' - if you pass through which aside nav to call, and 'help_centre' for the current_path value you could make the template generic for any page with content and a right hand column

**Comment by vidhyamanisankar** [comment]
> 



> Should really be page_body, not page_boby
> 
> It may also be worth looking at making the template generic rather than specific for 'About' - if you pass through which aside nav to call, and 'help_centre' for the current_path value you could make the template generic for any page with content and a right hand column
 there are 2 major difference between 'about' & 'help category' which blocks the same template will have been used in. for example- 'help category' template uses the component 'onsSectionNavigation' but 'about' template doesn't need that, title used for 'relatedcontent' varies for both templates. So we need to pass large number of parameters to render_template to reuse the same template. I think, it is not nice in terms of readability, maintainability. so leave as it- 'about' & 'help category' use separate template.

**Review by Paul-Joel — APPROVED** [review]

**Comment by vidhyamanisankar** [comment]
created a new branch to cover this change.

**Comment by vidhyamanisankar** [comment]
created new branch to this change.

**Pull request closed without merging**
