### PR TITLE
Selenium updated to the latest version & readme updated to reflect th…

### PR DESCRIPTION
**Pull request by sanjeevz3009**
# Description

Our Selenium test suite was failing due to Chrome driver issues. The issue occurred because of the Chromium team restructuring their drivers for the new Chrome-for-Testing drivers.

Fix:

- I upgraded Selenium to its latest version of 4.11.2 from 4.10.0. It fixed the Chrome driver issues. I also updated my local Chrome browser to the latest version of 116.0.5845.96 to ensure there are no errors.
- The README has also been updated to reflect the changes.

If you have not checked any of the lists below explain why here.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

Code comment not necessary in this instance.

## **Definition of Done**
**Code and merges**

- [ ] Code to be commented on where applicable 
- [x] Documentation updated where required 
- [x] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [x] I have linted the code

**Testing**

- [x] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [x] I have run the behave command to check the selenium behaviour tests pass locally
- [x] Acceptance criteria met

**Other Checks**
- [x] I have performed a self-review of my own code
- [x] I have checked for spelling errors
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes don't break anything unexpected
- [x] I have checked and updated the security.txt file where required
- [x] Up to date with the main branch

### CODE REVIEW

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://dup2kzo1n7yqj.cloudfront.net/
cloudfront_id=E10GBS60QQK66X

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://dup2kzo1n7yqj.cloudfront.net/
cloudfront_id=E10GBS60QQK66X

**Comment by jhmjam** [comment]
Hi mate this is similar to you other PR?

Also has this been tests locally?

Good work though :)

**Comment by sanjeevz3009** [comment]
> Hi mate this is similar to you other PR?
Yes, it's because I also wanted to use Poetry in this branch to make things easier instead of Pipenv as we aren't using that anymore.
> 
> Also has this been tests locally?
The tests are all passing locally =) You can pull down this branch and test it for yourself. README is also updated to show how to run the tests per the changes you made last time ;)
> 
> Good work though :)

**Comment by jhmjam** [comment]
Nice will test it now

**Review by jhmjam — APPROVED** [review]

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://dup2kzo1n7yqj.cloudfront.net/
cloudfront_id=E10GBS60QQK66X

**Pull request merged**
