### PR TITLE
Integrating Contentful CMS to SML Portal Web App

### PR DESCRIPTION
**Pull request by sanjeevz3009**
I have successfully integrated Contentful headless CMS into the SML Portal Web App.

Users will be able to add, delete & edit content for the following pages:
  - Home page
  - Methods Catalogue page
  - Methods table within method catalogue page
  - Individual method pages
  - About page

This is a demo branch, to show how this CMS system works.

### CODE REVIEW

**Comment by sanjeevz3009** [comment]
The deployment will fail as environment variables aren't set for GitHub CI/ CD.

**Comment by sanjeevz3009** [comment]
Deployment won't pass currently as environment variables aren't set for GitHub Actions CI /CD yet, regarding contentful SPACE_ID & CDA Keys.

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://de7t2noln9mcn.cloudfront.net/
cloudfront_id=E363WL6F5D40JG

**Comment by sanjeevz3009** [comment]
I am deleting this out-of-date branch. All the latest CMS code is now in the main branch =)

**Comment by sanjeevz3009** [comment]
I am deleting this out-of-date branch. All the latest CMS code is now in the main branch =)

**Pull request closed without merging**
