### PR TITLE
SPP-10105-add-beta-banner-and-feedback

### PR DESCRIPTION
**Pull request by joepercival**
# Description

MDQ have asked the the statisticalmethodslibrary website have a banner indicating the service is in Beta. This banner should also include a link in order for users to send feedback. This PR implements this banner and a mailto feedback link addressed to smlhelp@ons.gov.uk. 

Code has not been commented and documentation has not been provided as it is not necessary for this PR

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

## **Definition of Done**
**Code and merges**

- [ ] Code to be commented on where applicable 
- [ ] Documentation updated where required 
- [x] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [x] I have linted the code

**Testing**

- [x] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [x] I have run the behave command to check the selenium behaviour tests pass locally
- [x] Acceptance criteria met

**Other Checks**
- [x] I have performed a self-review of my own code
- [x] I have checked for spelling errors
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes don't break anything unexpected
- [x] I have checked and updated the security.txt file where required
- [x] Up to date with the main branch

### CODE REVIEW

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by JasonBellONS** [comment]
@joepercival something i've realised thats probably not been mentioned, when making commits to the sml repo can you please use the angular commit message format
https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format
basically when adding commit messages add
BREAKING_CHANGE: "message", (use when incompatibilities with previous versions would be introduced, less relevant with the website)
feat: "message", (use when adding new features that dont affect any other functionality)
fix: "message" (use when fixing existing functionality that doesn't work as intended)

these messages are needed for the CI version increment to properly document changes,

you can also optionally use
ci:
docs:
test:
if you have changes that you dont want to cause a version increment for

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://du196w62cqjc5.cloudfront.net/
cloudfront_id=E2DR8EG5UIU8LO

**Review by jhmjam — APPROVED** [review]

**Pull request merged**
