### PR TITLE
Spp11901

### PR DESCRIPTION
**Pull request by JasonBellONS**
Contentful audit script created which generates an HTML file displaying changes between two environments, as well as comparisons where relevant, see below for example:
image
image

### CODE REVIEW

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d295q5tw9olb8a.cloudfront.net/
cloudfront_id=E364B7XGOELOGS

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d295q5tw9olb8a.cloudfront.net/
cloudfront_id=E364B7XGOELOGS

**Comment by gibbardsteve** [comment]
I think a quick show and tell will work well to iron out some of the questions I have.  A couple below:

Can we make mapping back to the website section a bit easier?
E.g in Contentful we have content types of:

- Home Page
- Methods Catalogue Page
- Methods Table and Summary
- Help Centre
- Help Centre Method
- About Page
- Accessibility Page
- Privacy Page

It would be good to outline the content type where a change has occurred.

If we built a json structure it might prove useful for writing the html but also for automating this or integrating it with email etc e.g if at a later date we want to summarise the changes in an email as part of the build process.

"change_summary":{
    "added":  {
         "total":1,
         "affected_sections":["Help Centre"]
    },
   "edited": {
        "total":2,
        "affected_sections":["About Page","Privacy Page"]
   },
   "deleted": {
        "total":1,
        "affected_sections":["Methods Table and Summary"]
   }
},
"entries":[
{
  "change_type": "edit"
  "section": "Help Centre"
  "change_title": "Troubleshooting"
  "change_summary": {
     "id_diff":"",
     "title_diff":"",
     "content_diff":"",
     "category_diff":""
  }
}
]

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d295q5tw9olb8a.cloudfront.net/
cloudfront_id=E364B7XGOELOGS

**Comment by JasonBellONS** [comment]
Amended to also include a .json file overview of changes, example attached
[audit_report.json](https://github.com/user-attachments/files/17904384/audit_report.json)

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d295q5tw9olb8a.cloudfront.net/
cloudfront_id=E364B7XGOELOGS

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d295q5tw9olb8a.cloudfront.net/
cloudfront_id=E364B7XGOELOGS

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d295q5tw9olb8a.cloudfront.net/
cloudfront_id=E364B7XGOELOGS

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d295q5tw9olb8a.cloudfront.net/
cloudfront_id=E364B7XGOELOGS

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://d295q5tw9olb8a.cloudfront.net/
cloudfront_id=E364B7XGOELOGS

**Review by joepercival — APPROVED** [review]
Looks good 👍

**Pull request merged**
