### PR TITLE
Add more description to the PEP8 link

### PR DESCRIPTION
**Pull request by joepercival**
# Description

This pull request is to amend the PEP8 link in the coding standards page in order to make it more descriptive, this will enable all users to understand the purpose of the link in their journey.

Code has not been commented and documentation has not been written because it is not necessary for this PR.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

## **Definition of Done**
**Code and merges**

- [ ] Code to be commented on where applicable 
- [ ] Documentation updated where required 
- [x] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [x] I have linted the code

**Testing**

- [x] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [x] I have run the behave command to check the selenium behaviour tests pass locally
- [x] Acceptance criteria met

**Other Checks**
- [x] I have performed a self-review of my own code
- [x] I have checked for spelling errors
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes don't break anything unexpected
- [x] I have checked and updated the security.txt file where required
- [x] Up to date with the main branch

### CODE REVIEW

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://dmabjpfy6c9i0.cloudfront.net/
cloudfront_id=EZC4HJDSRP5FQ

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://dmabjpfy6c9i0.cloudfront.net/
cloudfront_id=EZC4HJDSRP5FQ

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://dmabjpfy6c9i0.cloudfront.net/
cloudfront_id=EZC4HJDSRP5FQ

**Review by gibbardsteve — APPROVED** [review]
Looks good Joe - first PR in the bag. 👍

**Comment by ons-spp-machine-user** [comment]
DEPLOY_URL=https://dmabjpfy6c9i0.cloudfront.net/
cloudfront_id=EZC4HJDSRP5FQ

**Pull request merged**
