### PR TITLE
SPP-8416-Update-Method-Titles

### PR DESCRIPTION
**Pull request by sanjeevz3009**
# Description

- This ticket was to update data adjustment and thousand pound correction in the methods catalogue table to make their text style/ format consistent with the other method names on the table.
- I have also made the method summary tests more generic & reusable.

Documentation & code comments are not required for this ticket as this ticket was a simple UI change.

https://jira.ons.gov.uk/browse/SPP-8416

Please include the link to the relevant Jira ticket here for ease of cross-referencing.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Technical Enhancements

# Checklist:

If any of these are not completed, please explain why in the notes.

## **Definition of Done**
**Code and merges**

- [ ] Code to be commented on where applicable 
- [ ] Documentation updated where required 
- [x] Have considered non-functional requirements such as Security, Performance, Scalability, and Fault Tolerance
- [x] I have linted the code

**Testing**

- [x] All levels of acceptance test are passing (automated, integration, manual, accessibility, etc.)
- [x] I have run the behave command to check the selenium behaviour tests pass locally
- [x] I have run the pytest command (see tests/README.md) to check that unit tests pass locally
- [x] Acceptance criteria met

**Other Checks**
- [x] I have performed a self-review of my own code
- [x] I have checked for spelling errors
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added the JIRA ticket link to this PR
- [x] My changes don't break anything unexpected
- [x] I have checked and updated the security.txt file where required
- [x] Up to date with the main branch

### CODE REVIEW

**Comment by jhmjam** [comment]
You also need to do it on their relevant pages :)

**Review by jhmjam — CHANGES_REQUESTED** [review]
Need to update relevant pages as well

**Comment by sanjeevz3009** [comment]
> Need to update relevant pages as well

The content/ values for the methods table and the individual method summary pages get pulled from the jsonnet files and updating it there updates it across to the methods table and its relevant summary pages =)

**Review by jhmjam — APPROVED** [review]

**Comment by jhmjam** [comment]
Looks good to me well done :)

**Review by jhmjam — APPROVED** [review]

**Pull request merged**
